[package]
name = "tui-realm-textarea"
version = "1.1.2"
authors = ["Christian Visintin"]
edition = "2021"
categories = ["command-line-utilities"]
description = "textarea component for tui-realm"
documentation = "https://docs.rs/tui-realm-textarea"
homepage = "https://github.com/veeso/tui-realm-textarea"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm-textarea"

[dependencies]
cli-clipboard = { version = "^0.4.0", optional = true }
lazy-regex = "^2.3.0"
tuirealm = { version = "^1.9.0", default-features = false, features = [ "derive" ]}
tui-textarea = { git = "https://github.com/erak/tui-textarea.git", branch = "textwrap" }

[dev-dependencies]
crossterm = "^0.25"
pretty_assertions = "^1.0.0"
tui-realm-stdlib = "^1.1.6"

[features]
default = ["with-crossterm"]
clipboard = ["cli-clipboard"]
search = ["tui-textarea/search"]
with-crossterm = ["tuirealm/with-crossterm"]
with-termion = ["tuirealm/with-termion"]

[[example]]
name = "demo"
path = "examples/demo.rs"
